// GENERATED by scripts/generate-images.mjs — do not edit by hand.
// Run `npm run images` after changing anything in assets/masters/.

export interface GeneratedImage {
  /** Intrinsic size of the fallback file, for reserving layout space. */
  width: number;
  height: number;
  /** Variant widths that exist on disk, ascending. */
  widths: number[];
  /** Tiny inlined preview, painted under the image while it loads. */
  blur: string;
}

export const generatedImages: Record<string, GeneratedImage> = {
  "/artworks/art-01.jpg": {
    "width": 1600,
    "height": 1067,
    "widths": [
      480,
      960,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAACQBACdASoUAA0APu1iqU2ppaOiMAgBMB2JbACdMoRwFf/gNDofFOkCeoB2LSAA/ltZ4DBhlBGocIhWb6i/N85wI436wYWSbSM9hRNGkfUTJHnHJUaEnYeZdAQXJnEgnhwe+U0ngR8QQIB1xNyHfkpRAEQSJSfKEfrOEXDOhNdtztg6gHUAAA=="
  },
  "/artworks/art-02.jpg": {
    "width": 1600,
    "height": 2000,
    "widths": [
      480,
      960,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRgYBAABXRUJQVlA4IPoAAACwBgCdASoUABkAPu1srFEppaQiqAqpMB2JbACsMoM8RmqUoHwDiBcNBoo5G4k2QtC6/Os2P7hUz5QOwMNYAAD+6SLBpFcHHPnz7/bO20DDbcCl71PZCwx0xBhZkmUoZDoVJ7b+97ezCm78vO4mD1rSQvoHhmzXqlflNvEcjfGqzw/Y5zz0hV8kGxROqI2gHrQkbeE4exjpxky0UC3rC8iM86Gv5uFSa/4eg5yeSpT+AOy09neEe35LtyeUsYmpgFgX5MFzwRUSM415rq3NaoAlvOln4jfmJ5oYo+Xzkhkl6Ks6jDgy2NqqI80qANDbOPks8aXYrqa/QAAA"
  },
  "/artworks/art-03.jpg": {
    "width": 1600,
    "height": 2000,
    "widths": [
      480,
      960,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRvIAAABXRUJQVlA4IOYAAADQBQCdASoUABkAPu1srFEppaQiqAqpMB2JZgCuHb4DldELAFXaH+H7Vp3Cxk2Cb/+JiKuAVaAAAPa+ZweMQmjupwTpae+PxHHUq1rlOn+xGr9H0xJAYqTPbOefnCod1XsEL4TaRE3xpYLhVLZAjMm8MVKi5iAx52Xdlku/Dh8ffgMCZP5dyiOOSV03sTIYkWZkj44Ot6c3h9yzxhQGUbGP/z3TWrZumGH7jB7sU2P7A+Y7SjkHVkz3S6fDd4Zw7bdini/r/hp4bw+creHPBU+RsN+2E5odD7Xrie13HDtLeLKoZIAAAA=="
  },
  "/artworks/art-04.jpg": {
    "width": 1440,
    "height": 1799,
    "widths": [
      480,
      960
    ],
    "blur": "data:image/webp;base64,UklGRgYBAABXRUJQVlA4IPoAAADQBgCdASoUABkAPu1gq1AppSOisBgIATAdiWwAsR7jgP80CGe8fI10ImCW3GYC9PHTzt80hWpk9aXvpEDoyAAA/hqhtSdv/eE/X12kvw7U7/XKmjvFwF82N9QukIUG/P4RzgS3V45TlbIjnAv5ocaYVnOZ/cXOfayXJgJ9n4CA9Q13xzY60GZ6zJlpLhX5jaApiTPU6bVNxDS81LeR28qCp/v5gCgY7NpoQtRLNjqzpoh7Klkx2Sr6pRioPBWFNGk1kj1u0fItTlbH7JM4mdn8FV8rUQzKAXLC8ZnTDb4Aw5qMJNqlKMuhj3bd98VGh4k16JJK1uneNEAA"
  },
  "/artworks/img-5411.jpg": {
    "width": 1152,
    "height": 2048,
    "widths": [
      480,
      960
    ],
    "blur": "data:image/webp;base64,UklGRuIAAABXRUJQVlA4INYAAAAwBgCdASoUACQAPu1urFGppiQipWzJMB2JQBlaraCj8X7L6vqnLEkt8cViidXggvu5AWpVjbDBkcosAP7zcCg7ocN8pPiev1yHoNpv+iioWwf5YR9XQLQFNU2C0cNUwvbV7ilD4TpsIdAjuGYqD9n5STlCL6egDRdf7AKNlOXHExQbs6r5BB04plFFg9jPuSsjG9q7r2+eX9G1y1I8aAkKc3pWsKAMHt+12teFWo2G/EFI1dxQpPvCGSCp6/ykGNaxVbBEIaRozWAmzvd/Oop1UdUWboAA"
  },
  "/artworks/img-6996.jpg": {
    "width": 1152,
    "height": 2048,
    "widths": [
      480,
      960
    ],
    "blur": "data:image/webp;base64,UklGRtAAAABXRUJQVlA4IMQAAACwBQCdASoUACQAPu1gq0+ppSOjMBVaqTAdiWgAt80LwJ0icASkGZKbJJT1JiabZjz8ajGb1BAA/ucVEzn+ZT6w76BPyiwTsM3y4elN3xm82Y9L2AwauFfBQOxe5opVl5drmyXmwXCCMgwfICjynOVGxHvn82jfdwp01fHBj+KJ4/rI9zJnupuiSYEe3r9UvzXJsi2XurmfwWmC4u9nxutPEexBnUt1Q6UmwEXIrYOFXEG1UR8WfVYNMecXOyh7ROiOYAAA"
  },
  "/artworks/img-7038.jpg": {
    "width": 1152,
    "height": 2048,
    "widths": [
      480,
      960
    ],
    "blur": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAAAQBQCdASoUACQAPu1krE2ppaSjKqwBMB2JYwC/7BZtRaUML2QfaXALv+7qdnT54keAAP7ftkL90JbduLFwVkuS4ScDvr38fQeE1H3VvgAM4PvrzISEzHzefz2JDPohcVSpGwSu6B/II6ZehAeitV2OfhVx5bNBfjPP+X9YXqSLjuIlM5Jo+zyElZYyhn3AmNm+Ast5raLCCPi48dDgxaHOPAAAAA=="
  },
  "/artworks/img-7645.jpg": {
    "width": 1600,
    "height": 2000,
    "widths": [
      480,
      960,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRtoAAABXRUJQVlA4IM4AAABQBQCdASoUABkAPu1qrlCppaQiqAqpMB2JaACdITYgwAv9KEH8ZHTTYI21vqjcZ5X78IAA9rt2jFAtEOEwFyz9qDMrFc2a4aC/QKCNukgInf26w2DMCXt7c+pBdR+F4Qx2YDvskmYZvioF5xmH0qUbz2FJgaX3X9Ij+kSDEwL0EV7VUpxG6tuL3fvVPtiU7OCe5p6EKCEhC7x0rMtt1LBkukFBS97be5L7hlLE7j0HLOjqSM9jgzRFRzWa10g14xkdgsDJQE6XBW500PvAAA=="
  },
  "/artworks/img-8293.jpg": {
    "width": 1600,
    "height": 2000,
    "widths": [
      480,
      960,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRggBAABXRUJQVlA4IPwAAADQBQCdASoUABkAPu1urlIppiQiqAgBMB2JZgC09BXSvmduQ2UHofAB2I9GO5Iz2Y3xLW1zE+k4AP6tJFDFSDH3QojQ4VEywEmIYmppQ3Lil9lydjF0TDyXDhhMvgfwrQyDvfgT1RK2hvcaSXaCHwyOl4zG2NRsmf0k9q7UI5IwVGBFABhw9LkQX8yLjpxpNDjYtXBS7X8umYuEnivHcBSdT+egBgyQ84SqbhT3Et66rTJblmfsU1uYf4kRfd+GpFUpkuXIYtHq5l3YP+Xdy7zgMjUALYMTOeKxboy5v2EqyzJ7mGrTfXaXmwB1u993KWHXwa5n7k+dQR0VAAA="
  },
  "/artworks/img-9435.jpg": {
    "width": 1600,
    "height": 1999,
    "widths": [
      480,
      960,
      1600
    ],
    "blur": "data:image/webp;base64,UklGRuIAAABXRUJQVlA4INYAAAAQBQCdASoUABkAPu1sq1EppaOiqAqpMB2JbACdMxL8CdFgaYJGOavf9yhiWF68zaNgAP5px9s8PvGLCG9KYyuxOzkRESsAkimmBQRbJh6SXAP1AUSsdkmM2E/W1u+EaHYmGDHO+szyZapD/kMoKWFV5u48WM62H0lYqt7SxoyXYQZAy95LdfgOORYL0+X5feRn5fqIrpiNZCK7reaMkUrfKdc358j1uoMOnpGLoDtKQERcqpzdoW9d4HPzW4B1aNhTODMR7B9MK/Othv1D2+48M1urgAAA"
  }
};
