/**
 * Generates the responsive image variants served from /artworks.
 *
 * Sources are the full-resolution masters in assets/masters/, which are NOT
 * served — only the derived, size-capped variants land in public/. Run this
 * after adding or replacing a master:
 *
 *   npm run images
 *
 * Output per master, e.g. art-01.jpg:
 *   public/artworks/art-01.jpg           1600px JPEG, the single legacy fallback
 *   public/artworks/art-01-{480,960,1600}.{avif,webp}
 *
 * Only AVIF and WebP get per-width variants — between them they cover the vast
 * majority of browsers, and anything older takes the one JPEG. Emitting a JPEG
 * at every width nearly doubled the output for traffic that does not exist.
 *
 * It also writes src/lib/generatedImages.ts so the app knows each image's
 * intrinsic size and which widths exist, without guessing at runtime.
 *
 * Outputs are build artefacts, not source: public/artworks is gitignored and
 * this runs automatically via predev/prebuild. Existing, up-to-date files are
 * skipped, so repeat runs are fast.
 */
import { readdir, mkdir, writeFile, stat } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const MASTERS = path.join(root, 'assets/masters');
const OUT = path.join(root, 'public/artworks');
const MANIFEST = path.join(root, 'src/lib/generatedImages.ts');

const WIDTHS = [480, 960, 1600];
const FALLBACK_WIDTH = 1600;

// Quality per format, tuned so AVIF and WebP stay visually clean on artwork.
const QUALITY = { avif: 55, webp: 78, jpeg: 82 };

/** True when `out` already exists and is at least as new as `src`. */
async function isFresh(out, src) {
  try {
    const [o, s] = await Promise.all([stat(out), stat(src)]);
    return o.mtimeMs >= s.mtimeMs;
  } catch {
    return false;
  }
}

async function main() {
  await mkdir(OUT, { recursive: true });
  const files = (await readdir(MASTERS)).filter(f => /\.(jpe?g|png)$/i.test(f)).sort();

  if (files.length === 0) {
    throw new Error(`No masters found in ${MASTERS}`);
  }

  const manifest = {};
  let totalBytes = 0;

  for (const file of files) {
    const name = path.parse(file).name;
    const src = path.join(MASTERS, file);
    const meta = await sharp(src).metadata();

    // Never upscale: a 1152px-wide master should not emit a 1600px variant.
    const widths = WIDTHS.filter(w => w <= meta.width);
    if (widths.length === 0) widths.push(meta.width);

    const emitted = [];
    let skipped = 0;
    for (const width of widths) {
      const base = sharp(src).resize({ width, withoutEnlargement: true });
      for (const format of ['avif', 'webp']) {
        const out = path.join(OUT, `${name}-${width}.${format}`);
        if (await isFresh(out, src)) {
          totalBytes += (await stat(out)).size;
          skipped++;
          continue;
        }
        const info = await base
          .clone()
          [format]({ quality: QUALITY[format] })
          .toFile(out);
        totalBytes += info.size;
      }
      emitted.push(width);
    }

    // Canonical fallback at the original URL, so /artworks/<name>.jpg always
    // resolves even if the manifest lookup or <picture> support fails.
    const fallbackPath = path.join(OUT, `${name}.jpg`);
    let fb;
    if (await isFresh(fallbackPath, src)) {
      const m = await sharp(fallbackPath).metadata();
      fb = { width: m.width, height: m.height, size: (await stat(fallbackPath)).size };
      skipped++;
    } else {
      fb = await sharp(src)
        .resize({ width: Math.min(FALLBACK_WIDTH, meta.width), withoutEnlargement: true })
        .jpeg({ quality: QUALITY.jpeg })
        .toFile(fallbackPath);
    }
    totalBytes += fb.size;

    // A 20px-wide WebP, inlined as a data URI. Painted as the image's own
    // background so there is a soft colour impression of the work instead of
    // an empty box while the real file downloads.
    const lqip = await sharp(src)
      .resize({ width: 20 })
      .webp({ quality: 40 })
      .toBuffer();

    manifest[`/artworks/${name}.jpg`] = {
      width: fb.width,
      height: fb.height,
      widths: emitted,
      blur: `data:image/webp;base64,${lqip.toString('base64')}`,
    };

    console.log(
      `${file.padEnd(16)} ${meta.width}x${meta.height} -> ${emitted.join(', ')}` +
        ` (+fallback ${fb.width}px)${skipped ? ` [${skipped} cached]` : ''}`
    );
  }

  const body = `// GENERATED by scripts/generate-images.mjs — do not edit by hand.
// Run \`npm run images\` after changing anything in assets/masters/.

export interface GeneratedImage {
  /** Intrinsic size of the fallback file, for reserving layout space. */
  width: number;
  height: number;
  /** Variant widths that exist on disk, ascending. */
  widths: number[];
  /** Tiny inlined preview, painted under the image while it loads. */
  blur: string;
}

export const generatedImages: Record<string, GeneratedImage> = ${JSON.stringify(
    manifest,
    null,
    2
  )};
`;
  await writeFile(MANIFEST, body);

  console.log(
    `\n${files.length} masters -> ${(totalBytes / 1024 / 1024).toFixed(2)} MB of variants`
  );
  console.log(`manifest: ${path.relative(root, MANIFEST)}`);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
