import { ArtistInfo, Artwork, Collection } from './types';

export const collections: Collection[] = [
  {
    id: 'selected-works',
    title: 'Selected Works',
    description: 'A curated selection of original paintings and studies.',
  },
];

export const artworks: Artwork[] = [
  {
    id: 'art-01',
    title: 'Selected Work I',
    year: 2025,
    medium: 'Oil on Canvas',
    dimensions: 'TBD',
    price: 0,
    imageUrl: '/artworks/art-01.jpg',
    collection: 'selected-works',
    featured: true,
    status: 'available',
  },
  {
    id: 'art-03',
    title: 'Selected Work III',
    year: 2025,
    medium: 'Oil on Canvas',
    dimensions: 'TBD',
    price: 0,
    imageUrl: '/artworks/art-03.jpg',
    additionalImageUrls: ['/artworks/art-02.jpg'],
    collection: 'selected-works',
    featured: true,
    status: 'available',
  },
  {
    id: 'art-04',
    title: 'Selected Work IV',
    year: 2025,
    medium: 'Oil on Canvas',
    dimensions: 'TBD',
    price: 0,
    imageUrl: '/artworks/art-04.jpg',
    collection: 'selected-works',
    featured: true,
    status: 'available',
  },
  {
    id: 'img-5411',
    title: 'Selected Work V',
    year: 2025,
    medium: 'Oil on Canvas',
    dimensions: 'TBD',
    price: 0,
    imageUrl: '/artworks/img-5411.jpg',
    collection: 'selected-works',
    featured: false,
    status: 'available',
  },
  {
    id: 'img-6996',
    title: 'Selected Work VI',
    year: 2025,
    medium: 'Oil on Canvas',
    dimensions: 'TBD',
    price: 0,
    imageUrl: '/artworks/img-6996.jpg',
    collection: 'selected-works',
    featured: false,
    status: 'available',
  },
  {
    id: 'img-7038',
    title: 'Selected Work VII',
    year: 2025,
    medium: 'Oil on Canvas',
    dimensions: 'TBD',
    price: 0,
    imageUrl: '/artworks/img-7038.jpg',
    collection: 'selected-works',
    featured: false,
    status: 'available',
  },
  {
    id: 'img-7645',
    title: 'Selected Work VIII',
    year: 2025,
    medium: 'Oil on Canvas',
    dimensions: 'TBD',
    price: 0,
    imageUrl: '/artworks/img-7645.jpg',
    collection: 'selected-works',
    featured: false,
    status: 'available',
  },
  {
    id: 'img-8293',
    title: 'Selected Work IX',
    year: 2025,
    medium: 'Oil on Canvas',
    dimensions: 'TBD',
    price: 0,
    imageUrl: '/artworks/img-8293.jpg',
    collection: 'selected-works',
    featured: false,
    status: 'available',
  },
  {
    id: 'img-9435',
    title: 'Selected Work X',
    year: 2025,
    medium: 'Oil on Canvas',
    dimensions: 'TBD',
    price: 0,
    imageUrl: '/artworks/img-9435.jpg',
    collection: 'selected-works',
    featured: false,
    status: 'available',
  },
];

export const artistInfo: ArtistInfo = {
  name: 'Sarah Sandia',
  bio: 'Sarah Sandia is a contemporary artist whose work explores color, memory, and the quiet moments of everyday life. Working primarily in oils, she captures scenes with warmth and depth.',
  email: 'studio@sarahsandia.art',
  socials: {
    instagram: 'https://instagram.com/#',
  },
  portraitUrl: '/artworks/img-9435.jpg',
};
