import { ArtistInfo, Artwork, Collection } from './types';

export const collections: Collection[] = [
  {
    id: 'selected-works',
    title: 'Selected Works',
    description: 'A curated selection of original paintings and studies.',
  },
];

export const artworks: Artwork[] = [
  {
    id: 'art-01',
    title: 'Un Verano en Nueva York',
    year: 2025,
    medium: 'Acrylics on canvas',
    dimensions: '30" x 24"',
    price: 0,
    imageUrl: '/artworks/art-01.jpg',
    collection: 'selected-works',
    featured: true,
    status: 'available',
  },
  {
    id: 'art-03',
    title: 'Heavenly',
    year: 2025,
    medium: 'Acrylics on canvas',
    dimensions: '12" x 18"',
    price: 0,
    imageUrl: '/artworks/art-03.jpg',
    additionalImageUrls: ['/artworks/art-02.jpg'],
    collection: 'selected-works',
    featured: true,
    status: 'sold',
  },
  {
    id: 'art-04',
    title: 'Untitiled',
    year: 2025,
    medium: 'Acrylics on canvas',
    dimensions: '8" x 10"',
    price: 0,
    imageUrl: '/artworks/art-04.jpg',
    collection: 'selected-works',
    featured: true,
    status: 'sold',
  },
  {
    id: 'img-5411',
    title: 'Flor Primera',
    year: 2025,
    medium: 'Spray Paint, Acrylics',
    dimensions: '43.5" x 37.5"',
    price: 0,
    imageUrl: '/artworks/img-5411.jpg',
    collection: 'selected-works',
    featured: false,
    status: 'sold',
  },
  {
    id: 'img-6996',
    title: 'Pond Lady',
    year: 2025,
    medium: 'Acrylics on Wood',
    dimensions: '40" x 40"',
    price: 0,
    imageUrl: '/artworks/img-6996.jpg',
    collection: 'selected-works',
    featured: false,
    status: 'available',
  },
  {
    id: 'img-7038',
    title: 'Selected Work VII',
    year: 2025,
    medium: 'Oil on Canvas',
    dimensions: 'TBD',
    price: 0,
    imageUrl: '/artworks/img-7038.jpg',
    collection: 'selected-works',
    featured: false,
    status: 'available',
  },
  {
    id: 'img-7645',
    title: 'With Grace, Always',
    year: 2025,
    medium: 'Acrylic on canvas',
    dimensions: '23.6" x 17.3"',
    price: 0,
    imageUrl: '/artworks/img-7645.jpg',
    collection: 'selected-works',
    featured: false,
    status: 'not-for-sale',
  },
  {
    id: 'img-8293',
    title: 'Le Cosmos et le Lotus',
    year: 2025,
    medium: 'Acrylics, newspaper board',
    dimensions: '20" x 16"',
    price: 0,
    imageUrl: '/artworks/img-8293.jpg',
    collection: 'selected-works',
    featured: false,
    status: 'sold',
  },
  {
    id: 'img-9435',
    title: 'Night Light',
    year: 2025,
    medium: 'Acrylics on canvas',
    dimensions: '16" x 20"',
    price: 0,
    imageUrl: '/artworks/img-9435.jpg',
    collection: 'selected-works',
    featured: false,
    status: 'available',
  },
];

export const artistInfo: ArtistInfo = {
  name: 'Sarah Sandia',
  bio: 'Sarah Sandia is a contemporary artist whose work explores color, memory, and the quiet moments of everyday life. Working primarily in oils, she captures scenes with warmth and depth.',
  email: 'studio@sarahsandia.art',
  socials: {
    instagram: 'https://instagram.com/artsandiaa',
  },
  portraitUrl: '/artworks/img-9435.jpg',
};
